import React, {Component} from 'react';

const styles = {
  header: {
    display: 'flex',
    alignItems: 'start',
    backgroundColor: '#1f1f1f'
  },
  title: {
    flex: 1,
    fontSize: '1.5rem',
    margin: '1rem'
  },
  date: {
    flex: 1,
    textAlign: 'right',
    margin: '1rem',
    color: 'white'
  }
};

export class Header extends Component {
  render() {
    return (
      <header style={styles.header}>
        <p style={styles.title}>
          <a href="http://amsteffensen.no" target="_blank" rel="noopener noreferrer">
            AMSteffensen Sails
          </a>
        </p>
        <p style={styles.date}>
          This page was Generated by FountainJS
          (Central European Summer Time)
        </p>
      </header>
    );
  }
}
